### ISSUE TITLE
Issue 3: Checks to see if there are files and if there is a directory in data/raw

### ISSUE THREAD

**Issue by EthanGardner18** [lboltz23/Web-Scraper-For-News-Websites#3]

**Comment by EthanGardner18** [comment]
The check makes sure the directory exists, if there are files, and if the files have data in them.

**Comment by EthanGardner18** [comment]
In run.py on line 34, there is a funciton call file_scrape.test_raw_file_write(). This reference is to file_scrape in module_2/file_scrape.py. This function then tests to see if the directory is there, if so grab all files, test to see if there is data. If there are any errors it will throw what is wrong. This function is on line 27-53

**Comment by lboltz23** [comment]
Looks good!
