### ISSUE TITLE
Issue 4: Checks to see if there are files and if there is a directory in data/processed

### ISSUE THREAD

**Issue by EthanGardner18** [lboltz23/Web-Scraper-For-News-Websites#4]

**Comment by EthanGardner18** [comment]
The function checks to see if the directory exists, if it does it sees if its empty, then it sees if there is data on the files.

**Comment by EthanGardner18** [comment]
In run.py on line 35, there is a funciton call  file_scrape.test_processed_file_write(). This reference is to file_scrape in module_2/file_scrape.py. This function then tests to see if the directory is there, if so grab all files, test to see if there is data. If there are any errors it will throw what is wrong. This function is on line 59-85.

**Comment by lboltz23** [comment]
Looks great!
