### ISSUE TITLE
Issue 8: Checks to see if there are files and if there is a directory in data/summary

### ISSUE THREAD

**Issue by EthanGardner18** [lboltz23/Web-Scraper-For-News-Websites#8]

**Comment by EthanGardner18** [comment]
In run.py on line 42, there is a funciton call summary.test_summary_files(). This reference is to file_scrape in module_3/chatgpt.py. This function then tests to see if the directory is there, if so grab all files, test to see if there is data. If there are any errors it will throw what is wrong. This function is on line 45-70

**Comment by lboltz23** [comment]
Looks great!
